# Generated by Django 5.2.4 on 2025-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's student email address.", max_length=254, unique=True)),
                ('school_domain', models.CharField(blank=True, help_text='The domain of the school (e.g., harvard.edu).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True if the user has clicked a verification link.')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
