# Generated by Django 5.2.4 on 2025-07-27 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['created_at'], 'verbose_name': 'Waitlist Entry', 'verbose_name_plural': 'Waitlist Entries'},
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='school_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
