# Generated by Django 5.2.4 on 2025-07-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_waitlistentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='logic.waitlistentry'),
        ),
    ]
